apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scylla-operator-role
rules:
  - apiGroups: ["scylla.scylladb.com"]
    resources: ["scylladbdatacenters", "scylladbs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["*"]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scylla-operator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scylla-operator-role
subjects:
  - kind: ServiceAccount
    name: scylla-operator
    namespace: scylla-operator

