# Specify desired Scylla Operator image
image:
  tag: latest

# Change log level
logLevel: 2

# Resources allocated to Scylla Operator pods
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi
