# Version information
scyllaImage:
  tag: 6.1.1
agentImage:
  tag: 3.3.3@sha256:40e31739e8fb1d48af87abaeaa8ee29f71607964daa8434fe2526dfc6f665920
# Cluster information
developerMode: true
datacenter: us-east-1
alternator:
  enabled: true
  insecureEnableHTTP: true
  insecureDisableAuthorization: true
  writeIsolation: always
serviceMonitor:
  create: false
racks:
  - name: us-east-1b
    members: 2
    storage:
      capacity: 5Gi
      storageClassName: scylladb-local-xfs
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 1
        memory: 1Gi
