# Namespace where the Scylla Cluster will be created
apiVersion: v1
kind: Namespace
metadata:
  name: scylla
---
# Scylla Cluster
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla-cluster
  namespace: scylla
spec:
  agentVersion: 3.3.3@sha256:40e31739e8fb1d48af87abaeaa8ee29f71607964daa8434fe2526dfc6f665920
  version: 6.1.1
  automaticOrphanedNodeCleanup: true
  alternator:
    port: 8000
    writeIsolation: only_rmw_uses_lwt
  sysctls:
    - fs.aio-max-nr=2097152
  datacenter:
    name: <gcp_region>
    racks:
      - name: <gcp_zone>
        scyllaConfig: scylla-config
        scyllaAgentConfig: scylla-agent-config
        members: 2
        storage:
          storageClassName: scylladb-local-xfs
          capacity: 20G
        resources:
          limits:
            cpu: 1
            memory: 2G
          requests:
            cpu: 1
            memory: 2G
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: failure-domain.beta.kubernetes.io/zone
                      operator: In
                      values:
                        - <gcp_zone>
          tolerations:
            - key: role
              operator: Equal
              value: scylla-clusters
              effect: NoSchedule
